language: node_js
node_js:
  - '5'
services:
  - redis
addons:
  code_climate:
    repo_token: d305ca3e3639d6f75f4aad29d6e68a7a138df46de5707a362b24d51ce2247423
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
